name: alumni
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  equatable: ^2.0.5
  auto_route: ^7.8.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_charts: ^23.1.43
  build_runner: ^2.4.6
  quickalert: ^1.0.2
  top_snackbar_flutter: ^3.1.0
  auto_route_generator: ^7.3.2
  cached_network_image: ^3.3.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.4
  multi_image_picker: ^4.8.01
  dotted_border: ^2.1.0
  url_launcher: ^6.2.1
  shimmer: ^3.0.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  flutter_screenutil: ^5.9.0
  talker_flutter: ^4.0.2
  talker_dio_logger: ^4.0.2
  talker_bloc_logger: ^4.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Intro
      fonts:
        - asset: font/intro_bold.ttf
        - asset: font/intro_regular.ttf

